# ----
# Site

title: ColdCutDeals
url: "http://www.coldcutdeals.com"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Cold Cut Deals - Find Hot Deals and Product Reviews
author:
  name: ColdCutDeals
  email: deals@coldcutdeals.com
  twitter: ColdCutDeals # twitter username without the @ symbol

# -----
# Build

permalink: pretty

collections:
  deals:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "deals"
    values:
      layout: "deal"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled: all

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background color used in the plan name and call to action.
  new_window: Open link in new window
  description: This is used for facebook shares of the page and google indexing
